### ISSUE TITLE
Error at startup

### ISSUE THREAD

**Issue by oikos1** [naddison36/tx2uml#1]
I start the program with either tx2uml <hash> -a <AlethioAPIkey>  or -e <EtherscanAPIKey>  and keep on getting :  UnhandledPromiseRejectionWarning: TypeError: Cannot set property 'to' of undefined

**Comment by naddison36** [comment]
The -a and -e options are working for me. What's the full command you are using? You can just replace the keys with XXX's when posting in here.
Also, if you set the `DEBUG` env var to `tx2uml`, it'll spit out the logs. eg `export DEBUG=tx2uml`

**Comment by oikos1** [comment]
Seems to be working now. I am unable to reproduce the issue. The command i was using :

tx2uml TXHASH -a XXXXX -e XXXXX
