### ISSUE TITLE
ERR! Failed at the node-plantuml@0.9.0 postinstall script.

### ISSUE THREAD

**Issue by rfikki** [naddison36/tx2uml#2]
c:\go-work\bin>npm link tx2uml --only=production
C:\Users\rfikk\AppData\Roaming\npm\tx2uml -> C:\Users\rfikk\AppData\Roaming\npm\node_modules\tx2uml\lib\tx2uml.js

> node-plantuml@0.9.0 postinstall C:\Users\rfikk\AppData\Roaming\npm\node_modules\tx2uml\node_modules\node-plantuml
> node scripts/get-vizjs.js

events.js:170
      throw er; // Unhandled 'error' event
      ^

Error: spawn java ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:247:19)
    at onErrorNT (internal/child_process.js:429:16)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
    at process.runNextTicks [as _tickCallback] (internal/process/task_queues.js:56:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:880:11)
    at internal/main/run_main_module.js:21:11
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:253:12)
    at onErrorNT (internal/child_process.js:429:16)
    [... lines matching original stack trace ...]
    at internal/main/run_main_module.js:21:11
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-plantuml@0.9.0 postinstall: `node scripts/get-vizjs.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-plantuml@0.9.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\rfikk\AppData\Roaming\npm-cache\_logs\2020-02-26T15_40_39_835Z-debug.log

**Comment by naddison36** [comment]
Do you have Java installed? I need to add that to the install instructions as it's needed by PlantUML

**Comment by rfikki** [comment]
Probably not on that machine. It was not stated as a requirement. I will install it.

**Comment by rfikki** [comment]
Worked just fine. Thanks for the help.

C:\Users\rfikk>npm link tx2uml --only=production
C:\Users\rfikk\AppData\Roaming\npm\tx2uml -> C:\Users\rfikk\AppData\Roaming\npm\node_modules\tx2uml\lib\tx2uml.js

> node-plantuml@0.9.0 postinstall C:\Users\rfikk\AppData\Roaming\npm\node_modules\tx2uml\node_modules\node-plantuml
> node scripts/get-vizjs.js

graphviz was not found on the system. Downloading vizjs instead. See http://plantuml.com/vizjs. This may take a few minutes.
+ tx2uml@0.0.8
added 20 packages from 17 contributors in 4.889s
C:\Users\rfikk\node_modules\tx2uml -> C:\Users\rfikk\AppData\Roaming\npm\node_modules\tx2uml

**Comment by naddison36** [comment]
Great you have it working. I've updated the install instructions to state Java is required. Thanks for raising.
