### ISSUE TITLE
Unable to set Etherscan API Key env

### ISSUE THREAD

**Issue by sambacha** [naddison36/tx2uml#21]
For some reason I have to replace the value defined here:
https://github.com/naddison36/tx2uml/blob/5a9208fee85c844c4fa93a2999961df4a555a2ae/src/ts/clients/EtherscanClient.ts#L24

with my own etherscan API key, otherwise it will not accept my API Key for usage, and give me a `rate limit error`

*Note: my API key is Etherscan Pro*

Version: latest
Nodejs: 14/lts
OS: OSX 15.5.5

**Comment by naddison36** [comment]
you should be able to set your own API key using the`-k` or long-form `--etherscanKey` option.

**Comment by sambacha** [comment]
I know that, I tried both

**Comment by sambacha** [comment]
here is an example:

API Key works:
https://api.etherscan.io/api?module=transaction&action=getstatus&txhash=0xfc1da838abecb3d7298b3628b3c6e6d9302833995eb8ac7b13c02889f5a95835&apikey=6XENF1GSDZYRISER6X4KGF3VDNNFPI47H4


response in terminal
https://d.pr/i/Fc4pBR

**Comment by naddison36** [comment]
I see the problem. Thanks for reporting. Try v1.0.15 I just published

**Comment by sambacha** [comment]
thanks @naddison36 , much appreciated
