### ISSUE TITLE
 Failed to get transaction details for tx hash

### ISSUE THREAD

**Issue by sleepriverfish** [naddison36/tx2uml#23]
I try to run tx2uml 0xb2b0e7b286e83255928f81713ff416e6b8d0854706366b6a9ace46a88095f024, but get error message 'Failed to generate UML diagram VError: Failed to get transaction details for tx hash'.

export ARCHIVE_NODE_URL=https://api.archivenode.io/api key/nethermind
tx2uml 0xb2b0e7b286e83255928f81713ff416e6b8d0854706366b6a9ace46a88095f024
version: tx2uml@1.0.16

Is there anything wrong?

**Comment by naddison36** [comment]
If you are using Nethermind, you need to use the `--nodeType nether` option. The short form is just `-n nether`

**Comment by sleepriverfish** [comment]
I get same error after try to use --nodeType nether. Please refer below screen shot for detail.
![tx2uml](https://user-images.githubusercontent.com/6247627/132967722-a03b13ee-a835-4d39-a4e6-65baedc7cf14.png)

**Comment by naddison36** [comment]
It looks like a local change got published. Apologies for that.
Can you try again with v1.0.17

**Comment by sleepriverfish** [comment]
another issue occur
![image](https://user-images.githubusercontent.com/6247627/132973750-eecbd333-4483-4167-8741-e0aef903ae45.png)

let me try with stable version.

**Comment by naddison36** [comment]
What node version are you using? `flat` should be supported from Node 12.

**Comment by sleepriverfish** [comment]
Thanks for you, i upgrade node and it is working fine now.
