### ISSUE TITLE
TokenInfo deployed to Optimism mainnet

### ISSUE THREAD

**Issue by eierina** [naddison36/tx2uml#46]
While adding support for Optimism, I deployed the TokenInfo to Optimism mainnet

URL: https://optimistic.etherscan.io/address/0x149a692a94eEe18e7854CEA1CEaab557618D4D46

CODE: https://optimistic.etherscan.io/address/0x149a692a94eEe18e7854CEA1CEaab557618D4D46#code

**Comment by naddison36** [comment]
nice. I'll also deploy to some of the testnets can do a release

**Comment by naddison36** [comment]
I've added this to release v1.1.7
