### ISSUE TITLE
tx2uml.js missing execution attributes in v1.1.10 

### ISSUE THREAD

**Issue by eierina** [naddison36/tx2uml#52]
After building and running `npm link` tx2uml does not execute unless you do a chmod 775 lib/tx2uml.js
In v1.1.4 the chmod was not necessary, not sure whether this is a security choice or the attribute just got lost.

**Comment by naddison36** [comment]
this explains a number of things. Thanks.

this should fix the problem
```json
"build": "tsc --build ./tsconfig.json; chmod 775 lib/tx2uml.js",
```

I'll include this in the next 1.1.12 release

**Comment by naddison36** [comment]
Can you try Release v1.1.12
